"""
ppe_state.py

Maintains temporal PPE state for tracked workers.

This module handles:

1. Temporal PPE history
2. Violation confirmation
3. Person Track ID changes
4. Worker identity association using:
   - IoU
   - Center-point distance
   - Maximum missing frames
   - One-to-one assignment

Important:
The tracker ID generated by OC-SORT is NOT treated as the
permanent worker identity.

Example:

    OC-SORT ID 5
          ↓
      Worker 5
          ↓
    OC-SORT ID 68
          ↓
      Worker 5

The goal is to preserve the same canonical worker identity
when OC-SORT changes the Person Track ID.
"""

from collections import deque


class PPEStateTracker:
    """
    Maintains temporal PPE state for tracked workers.

    OC-SORT may change a Person's track ID during tracking.

    Example:

        Person ID 5
             ↓
        same physical worker
             ↓
        Person ID 68

    This class attempts to preserve the same canonical
    worker identity and PPE history.
    """

    def __init__(
        self,
        history_size=5,
        violation_threshold=3,
        max_missing_frames=30,
        bbox_match_threshold=0.30,
        center_distance_threshold=0.50
    ):
        """
        Parameters
        ----------
        history_size : int
            Number of recent frames stored for PPE history.

        violation_threshold : int
            Number of violation detections required to
            confirm a violation.

        max_missing_frames : int
            Maximum number of frames a worker can disappear
            before the worker history is removed.

        bbox_match_threshold : float
            Minimum IoU required for a possible worker match.

        center_distance_threshold : float
            Maximum normalized center distance allowed for
            a possible worker match.
        """

        self.history_size = history_size
        self.violation_threshold = violation_threshold
        self.max_missing_frames = max_missing_frames

        self.bbox_match_threshold = bbox_match_threshold
        self.center_distance_threshold = center_distance_threshold

        # -----------------------------------------------------
        # Worker history
        #
        # Key = canonical worker ID
        # -----------------------------------------------------

        self.worker_history = {}

        # -----------------------------------------------------
        # Maps OC-SORT Person Track ID
        # to canonical worker ID
        #
        # Example:
        #
        # {
        #     5: 5,
        #     68: 5
        # }
        #
        # This means OC-SORT IDs 5 and 68 belong
        # to the same physical worker.
        # -----------------------------------------------------

        self.track_to_worker = {}

        # Current processing frame
        self.frame_number = 0

        print("PPE State Tracker initialized.")

    # =========================================================
    # CREATE WORKER HISTORY
    # =========================================================

    def _create_worker_history(self, worker_id, bbox):
        """
        Creates history for a new worker.

        The first OC-SORT Person ID becomes the
        canonical worker ID.
        """

        self.worker_history[worker_id] = {

            # PPE history
            "helmet": deque(
                maxlen=self.history_size
            ),

            "vest": deque(
                maxlen=self.history_size
            ),

            "mask": deque(
                maxlen=self.history_size
            ),

            # Last known person bounding box
            "last_bbox": bbox,

            # Last frame where worker was seen
            "last_seen_frame": self.frame_number,

            # Confirmed PPE violations
            "confirmed_violations": [],

            # Current OC-SORT Person Track ID
            "current_track_id": worker_id
        }

        return worker_id

    # =========================================================
    # BOUNDING BOX IoU
    # =========================================================

    def _calculate_iou(self, bbox1, bbox2):
        """
        Calculates Intersection over Union.

        bbox format:
            (x1, y1, x2, y2)
        """

        x1_1, y1_1, x2_1, y2_1 = bbox1
        x1_2, y1_2, x2_2, y2_2 = bbox2

        intersection_x1 = max(
            x1_1,
            x1_2
        )

        intersection_y1 = max(
            y1_1,
            y1_2
        )

        intersection_x2 = min(
            x2_1,
            x2_2
        )

        intersection_y2 = min(
            y2_1,
            y2_2
        )

        intersection_width = max(
            0,
            intersection_x2 - intersection_x1
        )

        intersection_height = max(
            0,
            intersection_y2 - intersection_y1
        )

        intersection_area = (
            intersection_width
            * intersection_height
        )

        area1 = (
            max(0, x2_1 - x1_1)
            *
            max(0, y2_1 - y1_1)
        )

        area2 = (
            max(0, x2_2 - x1_2)
            *
            max(0, y2_2 - y2_1)
            if False
            else
            max(0, x2_2 - x1_2)
            *
            max(0, y2_2 - y1_2)
        )

        union_area = (
            area1
            +
            area2
            -
            intersection_area
        )

        if union_area <= 0:
            return 0.0

        return intersection_area / union_area

    # =========================================================
    # BOUNDING BOX CENTER
    # =========================================================

    def _get_bbox_center(self, bbox):
        """
        Returns the center point of a bounding box.
        """

        x1, y1, x2, y2 = bbox

        center_x = (
            x1 + x2
        ) / 2

        center_y = (
            y1 + y2
        ) / 2

        return center_x, center_y

    # =========================================================
    # NORMALIZED CENTER DISTANCE
    # =========================================================

    def _calculate_center_distance(self, previous_bbox, new_bbox):
        """
        Calculates normalized center-point distance.

        The Euclidean distance between the two bounding-box
        centers is normalized using the diagonal of the
        previous bounding box.

        Smaller value = better match.

        Example:

            0.05 -> very close
            0.20 -> close
            0.50 -> relatively far
            1.00 -> approximately one bbox diagonal away
        """

        previous_center_x, previous_center_y = (
            self._get_bbox_center(previous_bbox)
        )

        new_center_x, new_center_y = (
            self._get_bbox_center(new_bbox)
        )

        dx = (
            new_center_x
            -
            previous_center_x
        )

        dy = (
            new_center_y
            -
            previous_center_y
        )

        center_distance = (
            dx ** 2
            +
            dy ** 2
        ) ** 0.5

        # Previous bounding-box dimensions
        x1, y1, x2, y2 = previous_bbox

        bbox_width = max(
            1,
            x2 - x1
        )

        bbox_height = max(
            1,
            y2 - y1
        )

        bbox_diagonal = (
            bbox_width ** 2
            +
            bbox_height ** 2
        ) ** 0.5

        if bbox_diagonal <= 0:
            return float("inf")

        normalized_distance = (
            center_distance
            /
            bbox_diagonal
        )

        return normalized_distance

    # =========================================================
    # FIND EXISTING WORKER
    # =========================================================

    def _find_existing_worker(
        self,
        track_id,
        bbox,
        current_stable_ids
    ):
        """
        Attempts to determine whether a new OC-SORT Person
        Track ID belongs to an existing worker.

        Matching uses:

        1. Maximum missing frames
        2. IoU
        3. Center-point distance
        4. One-to-one assignment

        Matching score:

            60% IoU
            40% center-distance score

        A candidate is accepted when either:

            IoU >= bbox_match_threshold

        OR:

            normalized center distance
            <= center_distance_threshold

        IMPORTANT:
        Only Person bounding boxes are used here.

        PPE-object Track IDs are never used for worker
        identity association.
        """

        best_worker_id = None
        best_score = -1.0

        for worker_id, history in self.worker_history.items():

            # -------------------------------------------------
            # One-to-one assignment
            #
            # A worker already assigned in this frame
            # cannot be assigned to another Person.
            # -------------------------------------------------

            if worker_id in current_stable_ids:
                continue

            # -------------------------------------------------
            # Maximum missing-frame check
            # -------------------------------------------------

            frames_missing = (
                self.frame_number
                -
                history["last_seen_frame"]
            )

            if frames_missing > self.max_missing_frames:
                continue

            # -------------------------------------------------
            # Previous bounding box
            # -------------------------------------------------

            previous_bbox = history["last_bbox"]

            # -------------------------------------------------
            # IoU
            # -------------------------------------------------

            iou = self._calculate_iou(
                previous_bbox,
                bbox
            )

            # -------------------------------------------------
            # Center distance
            # -------------------------------------------------

            normalized_distance = (
                self._calculate_center_distance(
                    previous_bbox,
                    bbox
                )
            )

            # -------------------------------------------------
            # Matching conditions
            # -------------------------------------------------

            iou_match = (
                iou
                >=
                self.bbox_match_threshold
            )

            center_match = (
                normalized_distance
                <=
                self.center_distance_threshold
            )

            # -------------------------------------------------
            # If neither signal supports the match,
            # reject this candidate.
            # -------------------------------------------------

            if not iou_match and not center_match:
                continue

            # -------------------------------------------------
            # Convert center distance into a score.
            #
            # Smaller distance = better score.
            #
            # Example:
            #
            # distance = 0.10
            # score    = 0.90
            #
            # distance = 0.40
            # score    = 0.60
            # -------------------------------------------------

            distance_score = max(
                0.0,
                1.0 - normalized_distance
            )

            # -------------------------------------------------
            # Combined matching score
            #
            # IoU gets slightly higher importance.
            # -------------------------------------------------

            match_score = (
                0.6 * iou
                +
                0.4 * distance_score
            )

            # -------------------------------------------------
            # Keep the best candidate
            # -------------------------------------------------

            if match_score > best_score:

                best_score = match_score
                best_worker_id = worker_id

                print(
                    f"[MATCH CANDIDATE] "
                    f"Worker={worker_id} "
                    f"New OC-SORT ID={track_id} "
                    f"Missing={frames_missing} "
                    f"IoU={iou:.3f} "
                    f"CenterDist={normalized_distance:.3f} "
                    f"Score={match_score:.3f}"
                )

        return best_worker_id

    # =========================================================
    # RESOLVE WORKER ID
    # =========================================================

    def _resolve_worker_id(
        self,
        track_id,
        bbox,
        current_stable_ids
    ):
        """
        Resolves an OC-SORT Person Track ID to a canonical
        worker ID.

        Example:

            OC-SORT ID 5
                ↓
            Worker 5

            Later:

            OC-SORT ID 68
                ↓
            bbox matches Worker 5
                ↓
            Worker 5
        """

        # -----------------------------------------------------
        # 1. Track ID already known
        # -----------------------------------------------------

        if track_id in self.track_to_worker:

            worker_id = (
                self.track_to_worker[
                    track_id
                ]
            )

            if worker_id in self.worker_history:

                # -------------------------------------------------
                # Important:
                #
                # If this worker was already assigned earlier
                # in the current frame, do not allow another
                # detection to reuse the same canonical ID.
                # -------------------------------------------------

                if worker_id in current_stable_ids:

                    print(
                        f"[DUPLICATE MAPPING] "
                        f"OC-SORT ID={track_id} "
                        f"is already mapped to Worker={worker_id} "
                        f"in frame {self.frame_number}"
                    )

                    return worker_id

                return worker_id

        # -----------------------------------------------------
        # 2. New Track ID
        #
        # Try to match it with an existing worker.
        # -----------------------------------------------------

        worker_id = self._find_existing_worker(
            track_id,
            bbox,
            current_stable_ids
        )

        # -----------------------------------------------------
        # 3. Existing worker found
        #
        # This is the ID-switch case.
        # -----------------------------------------------------

        if worker_id is not None:

            old_track_id = (
                self.worker_history[
                    worker_id
                ]["current_track_id"]
            )

            print(
                f"[TRACK ID CHANGE] "
                f"Worker {worker_id}: "
                f"OC-SORT {old_track_id} "
                f"-> OC-SORT {track_id}"
            )

            # New OC-SORT ID now belongs
            # to the existing canonical worker.
            self.track_to_worker[
                track_id
            ] = worker_id

            return worker_id

        # -----------------------------------------------------
        # 4. Completely new worker
        #
        # The first OC-SORT Person ID becomes
        # the canonical Worker ID.
        # -----------------------------------------------------

        worker_id = track_id

        self._create_worker_history(
            worker_id,
            bbox
        )

        self.track_to_worker[
            track_id
        ] = worker_id

        print(
            f"[NEW WORKER] "
            f"OC-SORT {track_id} "
            f"-> Worker {worker_id}"
        )

        return worker_id

    # =========================================================
    # UPDATE
    # =========================================================

    def update(self, worker_status):
        """
        Updates temporal PPE state for all workers
        in the current frame.

        Parameters
        ----------
        worker_status : list[dict]
            Worker information returned by
            PPERules.evaluate().

        Returns
        -------
        list[dict]
            Worker information with stable worker IDs
            and temporal PPE status.
        """

        self.frame_number += 1

        updated_workers = []

        # -----------------------------------------------------
        # Stable worker IDs already assigned in this frame.
        #
        # Used to guarantee one-to-one assignment.
        # -----------------------------------------------------

        current_stable_ids = set()

        # =====================================================
        # PROCESS CURRENT WORKERS
        # =====================================================

        for worker in worker_status:

            # -------------------------------------------------
            # Person Track ID
            # -------------------------------------------------

            track_id = worker["track_id"]

            if track_id is None:
                continue

            # -------------------------------------------------
            # Person detection
            # -------------------------------------------------

            person = worker["person"]

            bbox = person.bbox

            # -------------------------------------------------
            # DEBUG
            # -------------------------------------------------

            print(
                f"[TRACK] "
                f"OC-SORT ID={track_id} "
                f"BBox={bbox}"
            )

            # -------------------------------------------------
            # Resolve canonical worker ID
            # -------------------------------------------------

            worker_id = self._resolve_worker_id(
                track_id,
                bbox,
                current_stable_ids
            )

            # -------------------------------------------------
            # Duplicate worker protection
            #
            # A canonical worker can appear only once
            # in a single frame.
            # -------------------------------------------------

            if worker_id in current_stable_ids:

                print(
                    f"[DUPLICATE WORKER] "
                    f"Worker {worker_id} already assigned "
                    f"in frame {self.frame_number}. "
                    f"Skipping OC-SORT ID={track_id}"
                )

                continue

            current_stable_ids.add(
                worker_id
            )

            # -------------------------------------------------
            # Get worker history
            # -------------------------------------------------

            history = self.worker_history[
                worker_id
            ]

            # -------------------------------------------------
            # Update latest tracking information
            # -------------------------------------------------

            history["last_seen_frame"] = (
                self.frame_number
            )

            history["last_bbox"] = bbox

            history["current_track_id"] = (
                track_id
            )

            # -------------------------------------------------
            # Store PPE evidence
            # -------------------------------------------------

            history["helmet"].append(
                worker["no_helmet"]
            )

            history["vest"].append(
                worker["no_vest"]
            )

            history["mask"].append(
                worker["no_mask"]
            )

            # -------------------------------------------------
            # Determine confirmed violations
            # -------------------------------------------------

            confirmed_violations = []

            # NO HARDHAT
            if self._is_violation_confirmed(
                history["helmet"]
            ):

                confirmed_violations.append(
                    "NO HARDHAT"
                )

            # NO SAFETY VEST
            if self._is_violation_confirmed(
                history["vest"]
            ):

                confirmed_violations.append(
                    "NO SAFETY VEST"
                )

            # NO MASK
            if self._is_violation_confirmed(
                history["mask"]
            ):

                confirmed_violations.append(
                    "NO MASK"
                )

            # Save confirmed violations
            history["confirmed_violations"] = (
                confirmed_violations.copy()
            )

            # -------------------------------------------------
            # Create output worker
            # -------------------------------------------------

            updated_worker = worker.copy()

            # Preserve the raw OC-SORT ID for Task 2 verification
            # before replacing track_id with the canonical worker ID.
            updated_worker["tracker_id"] = track_id

            # IMPORTANT:
            #
            # Replace the current OC-SORT ID with
            # the canonical worker ID.
            #
            # Example:
            #
            # OC-SORT ID 68
            #       ↓
            # Worker 5
            # -------------------------------------------------

            updated_worker["track_id"] = (
                worker_id
            )

            updated_worker[
                "stable_worker_id"
            ] = worker_id

            updated_worker[
                "confirmed_violations"
            ] = confirmed_violations.copy()

            # -------------------------------------------------
            # Build final status
            # -------------------------------------------------

            updated_worker["status"] = (
                self._build_status(
                    worker,
                    confirmed_violations
                )
            )

            updated_workers.append(
                updated_worker
            )

        # =====================================================
        # CLEANUP OLD WORKERS
        # =====================================================

        self._cleanup_old_workers()

        return updated_workers

    # =========================================================
    # VIOLATION CONFIRMATION
    # =========================================================

    def _is_violation_confirmed(
        self,
        history
    ):
        """
        Determines whether a PPE violation has enough
        recent evidence.
        """

        violation_count = sum(
            history
        )

        return (
            violation_count
            >=
            self.violation_threshold
        )

    # =========================================================
    # BUILD FINAL STATUS
    # =========================================================

    def _build_status(
        self,
        worker,
        confirmed_violations
    ):
        """
        Builds the final worker status.
        """

        # -----------------------------------------------------
        # Confirmed violations
        # -----------------------------------------------------

        if confirmed_violations:

            return " | ".join(
                confirmed_violations
            )

        # -----------------------------------------------------
        # Current PPE state
        # -----------------------------------------------------

        helmet_ok = worker["helmet"]
        vest_ok = worker["vest"]
        mask_ok = worker["mask"]

        # -----------------------------------------------------
        # Completely safe
        # -----------------------------------------------------

        if (
            helmet_ok
            and vest_ok
            and mask_ok
        ):

            return "SAFE"

        # -----------------------------------------------------
        # Insufficient evidence for confirmed violation
        # -----------------------------------------------------

        return "MONITORING"

    # =========================================================
    # CLEANUP OLD WORKERS
    # =========================================================

    def _cleanup_old_workers(self):
        """
        Removes worker histories that have not been seen
        for more than max_missing_frames.
        """

        expired_worker_ids = []

        # -----------------------------------------------------
        # Find expired workers
        # -----------------------------------------------------

        for worker_id, history in (
            self.worker_history.items()
        ):

            frames_missing = (
                self.frame_number
                -
                history["last_seen_frame"]
            )

            if (
                frames_missing
                >
                self.max_missing_frames
            ):

                expired_worker_ids.append(
                    worker_id
                )

        # -----------------------------------------------------
        # Remove expired worker histories
        # -----------------------------------------------------

        for worker_id in expired_worker_ids:

            print(
                f"[WORKER EXPIRED] "
                f"Worker {worker_id}"
            )

            del self.worker_history[
                worker_id
            ]

        # -----------------------------------------------------
        # Remove OC-SORT ID mappings belonging
        # to expired workers
        # -----------------------------------------------------

        expired_track_ids = []

        for (
            track_id,
            worker_id
        ) in self.track_to_worker.items():

            if (
                worker_id
                in
                expired_worker_ids
            ):

                expired_track_ids.append(
                    track_id
                )

        for track_id in expired_track_ids:

            del self.track_to_worker[
                track_id
            ]